Category page: coursebox, workshopbox & workshop page
e-PSHAD/PAD pull request #23
Opened 2022-03-01 15:20 UTC by mantecajc

J'ai modifié les éléments suivants : 
- Course boxes
- Workshop boxes
- Workshop registration page
- Notification d'inscription - message de succès
- Le style de la pagination

J'ai corrigé deux petits bugs sur le front : 
- J'ai supprimé la bordure qui apparaissait dans le fil d'Ariane dans la version mobile.
- Bug d'alignement dans le tableau de bord (éliminé le padding latéral)  : les cours n'étaient pas alignés avec le heading.

2022-03-02 15:21 UTC, denier-epnak requested changes

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        $coursesperpagepadplus = 10; // We have limited to 10 courses per page.
Voir option de la config Moodle ?

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        $instances = enrol_get_instances($course->id, false);
$enrol_instances

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +            $image = $this->image_url('default', 'theme_padplus');
voir image avec droits ok

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +            return html_writer::tag('div',
duplication with 305

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +    private function coursebox_contacts(core_course_list_element $course, string $rolelabel = null) {
Keep previous modifier + method name : protected function course_contacts(...)

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        $tags = '';
useless

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        if (!empty($tags)) {
if (empty($tags)) {
  return '';
}
...

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +    private function coursebox_enrolled_students($context) {
use $course param and instantiate $context here

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +    private function coursebox_info($course, $chelper, $context, $activitybox, string $rolelabel = null) {
private function coursecat_coursebox_details($course, $chelper, $contactbox, $enrolledstudentsbox, $buttonlabel, $boxclassname = '') {
        $output = html_writer::start_tag('div', array('class' => "info $boxclassname")));
        $output .= $this->course_tags($course);
        $output .= $this->course_name($chelper, $course);
        $output .= $this->course_summary($chelper, $course);
        $output .= $contactbox;
        $output .= $enrolledstudentsbox;
        $output .= html_writer::link(
             new moodle_url('/course/view.php', ['id' => $course->id]),
             $buttonlabel,
             array('class' => $course->visible ? 'btn btn-secondary' : 'btn btn-secondary disabled'));
        return $output;
}

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        $coursebox = true;
remove

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        foreach ($instances as $key => $value) {
extract predicate course_is_workshop($course) {
    $instances = enrol_get_instances($course->id, false);
    foreach ($instances as $key => $value) {
       if ($value->enrol == 'self' && $value->status == '0') {
                $coursebox = false;
            }
        }
}

if (course_is_workshop($course)) {
 .....
} else { // séquence
...
}

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        }
if (workshop) {
  $rolelabel = get_string('workshop-teacher', 'theme_padplus'); // 
  $enrolledstudentsbox = ''; // do no show enrolled student number for workshop
  $buttonlabel = ;
  $boxclassname = ;
} else {
  $rolelabel = null; // Use user role as label
  $enrolledstudentsbox = $this->coursebox_enrolled_students($context);
  $buttonlabel = ;
  $boxclassname = ;   
}
$contactbox = $this->coursebox_contacts($course, $rolelabel);
$content .= $this->coursebox_info($course, $chelper, $contactbox, $enrolledstudentsbox, $buttonlabel, $boxclassname);

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/scss/post.scss
> +@import 'post/components/coursebox-category-list.scss';
rename as coursebox

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/scss/post.scss
> +@import 'post/layouts/notifications.scss';
move to components

2022-03-02 15:21 UTC, denier-epnak commented on theme/padplus/scss/post/pages/_categories.scss
> +    nav:first-child.pagination { // Hide first pagination.
Hide top pagination

2022-03-03 11:48 UTC, mantecajc commented on theme/padplus/classes/output/core/course_renderer.php
> +        $coursesperpagepadplus = 10; // We have limited to 10 courses per page.
We can change the value of $perpage adding this to config.php: 

// Pagination
$CFG->coursesperpage = 12; // Set to 20 by default.

Should I add this code to config-docker.php and push it ?

2022-03-03 12:12 UTC, mantecajc commented on theme/padplus/classes/output/core/course_renderer.php
> +            $image = $this->image_url('default', 'theme_padplus');
I've added an image without copyright from here https://pixabay.com/fr/illustrations/al%c3%a9atoire-motif-rectangle-2403426/

2022-03-03 15:27 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        $coursesperpagepadplus = 10; // We have limited to 10 courses per page.
Ah en fait cette option est disponible via l'administration 
https://www.eig-epshad.com/admin/settings.php?section=coursecontact

En fait faut la rajouter dans la config auto pad-infra coursesperpage
  - # Set number of courses per page
    key: coursesperpage
    value: 10

2022-03-03 15:39 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +            $image = $this->image_url('default', 'theme_padplus');
C'est ... agressif. A voir avec Béa

2022-03-03 16:12 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +            $content .= $this->coursecat_coursebox_details($course, $chelper, $contactbox, $enrolledstudentsbox, $buttonlabel, $boxclassname = '');
Pourquoi on ne sort pas cette ligne du if/else vu que c'est la même que 278 ? $rolelabel et $boxclassname sont gérés en tant que paramètres optionnels.

```
        if ($this->course_is_workshop($course)) {
            $rolelabel = get_string('workshop-teacher', 'theme_padplus');
            $studentsbox = ''; // Do not show enrolled student number for workshop.
            $buttonlabel = get_string('btn-workshopbox', 'theme_padplus');
            $boxclassname = 'workshopbox';
        } else {
            $studentsbox = $this->coursebox_enrolled_students($course);
            $buttonlabel = get_string('btn-coursebox', 'theme_padplus');
        }
        $contactbox = $this->course_contacts($course, $rolelabel);
        $content .= $this->coursecat_coursebox_details($course, $chelper, $contactbox, $studentsbox, $buttonlabel, $boxclassname);
```

2022-03-03 16:15 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        $enrolledstudents = count_enrolled_users($context) - count_enrolled_users($context, 'mod/glossary:viewanyrating');
Faudrait qu'on trouve une permission plus explicite que 'mod/glossary:viewanyrating' pour distinguer les profs ? les stagiaires ?

2022-03-03 16:20 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +                $output .= $enrolledstudents;
fix indentation

2022-03-03 16:22 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +                $name = implode(", ", $rolenames).': '.
espace avant " : "

2022-03-03 16:22 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        $output .= get_string('participants-enrolled', 'theme_padplus') . ': ';
espace avant " : "

2022-03-03 16:25 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +    private function coursecat_coursebox_details($course, $chelper, $contactbox, $enrolledstudentsbox, $buttonlabel, $boxclassname = '') {
Line exceeds 132 characters; contains 138 characters

private function coursecat_coursebox_details($course, $chelper, $contactbox, $studentsbox, $buttonlabel, $boxclassname) {

2022-03-03 16:29 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +            $content .= $this->coursecat_coursebox_details($course, $chelper, $contactbox, $enrolledstudentsbox, $buttonlabel, $boxclassname = '');
fix Line exceeds 132 characters; contains 138 characters

2022-03-03 16:40 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        $enrolledstudents = count_enrolled_users($context) - count_enrolled_users($context, 'mod/glossary:viewanyrating');
mod/assign:viewgrades ? https://docs.moodle.org/311/en/Capabilities/mod/assign:viewgrades

2022-03-03 16:43 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +        $enrolledstudents = count_enrolled_users($context) - count_enrolled_users($context, 'mod/glossary:viewanyrating');
Pour avoir directement le nombre de stagiaires ?
`$enrolledstudents = count_enrolled_users($context, 'mod/assign:submit');`

https://docs.moodle.org/310/en/Capabilities/mod/assign:submit

2022-03-03 17:21 UTC, mantecajc commented on theme/padplus/classes/output/core/course_renderer.php
> +            $image = $this->image_url('default', 'theme_padplus');
Yes ! Je viens d'ajouter l'image de la pad de bordeaux en attendent l'image de Bea

2022-03-03 17:23 UTC, mantecajc commented on theme/padplus/classes/output/core/course_renderer.php
> +        $enrolledstudents = count_enrolled_users($context) - count_enrolled_users($context, 'mod/glossary:viewanyrating');
je prends !

2022-03-03 18:01 UTC, mantecajc commented on theme/padplus/classes/output/core/course_renderer.php
> +        $output .= html_writer::start_tag('div');
J'ai ajouté ce div pour fixer un petit bug de style

2022-03-04 09:25 UTC, denier-epnak commented on theme/padplus/classes/output/core/course_renderer.php
> +            $image = $this->image_url('default', 'theme_padplus');
Go avec image générée```

        if (is_null($image)) {
            $image = $this->get_generated_image_for_id($course->id);
        }
```

2022-03-04 15:13 UTC, merged